---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readxl)
library(dplyr)
library(janitor) # GROUP SUMMARY
library(readr) # MA TRAN PEARSON
library(strucchange) # KIEM DINH CHOW
library(plm) # KIEM DINH HAUSMAN
library(lmtest) # KIEM DINH Breusch-Pagan Test.
library(openxlsx)
library(ggplot2)
library(hrbrthemes)

#==================IMPORT===========================================================================
rm(list = ls()) # CLEAR
setwd("C:/Users/Vu Quang Nguyen/Working/KhoaLuanUEH/Dataset")

Output<- read_excel("C:/Users/Vu Quang Nguyen/Working/KhoaLuanUEH/Dataset/Report.xlsx", 
                    sheet = "Output")

Output<-select(Output,-1)
Output <- Output %>% 
  mutate(ID=row_number())

Output <- Output %>% 
  mutate(NhomNganh=`Nhom nganh`)

Output<-Output %>%  # HOSE = 1; HNX =2 ; UPCOM =3
  mutate(ID_San = ifelse(San == "HOSE", 1, 
                     ifelse(San == "HNX", 2, 3)))

Output %>%
  filter_at(vars(GRWTH,SIZE,PROF,LIQD,UNIQ,TANG,GDP,COVID,INDS), all_vars(!is.na(.))) %>%
  select(GRWTH,SIZE,PROF,LIQD,UNIQ,TANG,GDP,COVID) %>%
  summary()

Output
```

```{r}



#--------- SETTING REGRESSION

# POLS------------------------
pooling <- plm(STLEV ~ GRWTH + SIZE + PROF + LIQD + UNIQ + TANG +GDP +COVID,
          data = Output, 
          index = c("INDS","ID_Year"),
          model = "pooling")
summary(pooling)


# FE------------------------
fe <- plm(STLEV ~ GRWTH + SIZE + PROF + LIQD + UNIQ + TANG +GDP +COVID,
          data = Output, 
          index = c("INDS","ID_Year"),
          model = "within")
summary(fe)

#RANDOM EFFECT MODEL-------------------------------


# RE------------------------
re <- plm(STLEV ~ GRWTH +SIZE + LIQD +TANG + UNIQ, 
          data = Output, 
          index = c("INDS","ID_Year"),
          model = "random")
summary(re)



#_---------- TESTING
# LM TEST for Random vs OLS (Lagrange Multiplier Test - (Honda)), H0: OLS phù hợp, H1: REM Phù hợp
plmtest(pooling)

#LM TEST for Fixed vs OLS (F-test): H0 OLS phù hợp; H1: FEM phù hợp
pFtest(fe,pooling)

#Hausman Test for Fixed VS RANDOM: H0: REM Phù hợp; H1: FEM Phù hợp
phtest(re,fe)

```

```{r}
#=============================================================================================


# PEARSON TABULATE CORRELATION
Corr <- cor(Output %>% 
              na.omit %>% 
              select(GRWTH,SIZE,PROF,LIQD,UNIQ,TANG,GDP,COVID)) # lenh na.omit de loai bo dong na (missing value)

upper<-round(Corr,4)
upper[upper.tri(Corr)]<-""
upper<-as.data.frame(upper)
upper
View(upper)
```

```{r}

```
